name: Build and publish wheels

on:
  push:
    branches:
      - master
    tags:
      - '*'  # Triggers the workflow on version tags

permissions:
  contents: write
  actions: read
  
jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Replace version number
        run: |
          ls
          sed -i 's/2024.05.29/2025.01.28/g' README.md
          sed -i 's/2024.05.29/2025.01.28/g' doc/conf.py
          sed -i 's/2024.05.29/2025.01.28/g' meson.build
          sed -i 's/2024.05.29/2025.01.28/g' pyproject.toml
          sed -i 's/024.05.29/2025.01.28/g'  skfmm/__init__.py
      

      - name: Create branch and commit changes
        run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout -b replace-string-branch
         git add .
         git commit -m 'Update version'

      - name: Push changes
        run: git push origin replace-string-branch
      
      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
 
  build_wheels:
    needs: [build_sdist]
    name: Build ${{ matrix.arch }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: auto64
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-22.04-arm
            arch: aarch64
          - os: macos-13
            arch: x86_64
            macos_deployment_target: "13.0"
          - os: macos-14
            arch: arm64
            macos_deployment_target: "14.0"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
      
      - name: Wheels
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_SKIP: "*pp3* *cp38*"
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
          CIBW_ENVIRONMENT_MACOS:
            MACOSX_DEPLOYMENT_TARGET=${{ matrix.macos_deployment_target }}
          CIBW_TEST_REQUIRES: numpy
          CIBW_TEST_COMMAND: |
           python -c "import skfmm, sys; sys.exit(skfmm.test())"
           pip install numpy==1.26.4
           python -c "import skfmm, sys; sys.exit(skfmm.test())"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
          retention-days: 5
  
  publish:
    name: Publish on GitHub and PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist
      
      - uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-22.04-x86_64
          path: dist
      
      - uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-22.04-arm-aarch64
          path: dist
      
      - uses: actions/download-artifact@v4
        with:
          name: wheels-macos-13-x86_64
          path: dist
      
      - uses: actions/download-artifact@v4
        with:
          name: wheels-macos-14-arm64
          path: dist
      
      - uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest-auto64
          path: dist

      - name: Upload Wheels to PyPI
        # release on every tag
       # if: ${{ github.event_name == 'release' && github.ref_type == 'tag' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip_existing: true
          repository_url: https://test.pypi.org/legacy/  # To test
         
    #  - name: Create GitHub Release
    #    uses: softprops/action-gh-release@v1
    #    with:
    #      files: dist/*
    #      body_path: ./release_notes.md
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  
